language: scala
sudo: false
scala:
  - 2.10.7
  - 2.11.12
jdk:
  - openjdk7
addons:
  hostname: localhost
matrix:
  include:
  - scala: 2.12.4
    jdk: oraclejdk9
  - scala: 2.12.4
    jdk: oraclejdk8
  - scala: 2.13.0-M3
    jdk: oraclejdk8
